import { describe, expect, it, vi } from 'vitest'
import { effectScope, nextTick } from 'vue'
import { MediaApiError } from '../lib/mediaModel'
import { useAuthoritativeDvrWindow } from './useAuthoritativeDvrWindow'
import type { MediaClient } from '../lib/mediaClient'

const descriptor = (id: string) => ({ schema_version: '1.0.0' as const, playback_window_id: id, capture_session_id: 's', mode: 'archive' as const, mapping_version: 1, timeline_capture_start_us: '0', timeline_capture_end_us: '100', window_capture_start_us: '0', window_capture_end_us: '100', presentation_origin_capture_us: '0', target_player_media_time_us: '0', manifest_url: '/m', expires_at: new Date(Date.now() + 100000).toISOString(), has_more_before: false, has_more_after: false })
const anchor = (frame: string, time = '10') => ({ schema_version: '1.0.0' as const, capture_session_id: 's', playback_window_id: 'w', mapping_version: 1, capture_epoch_id: 'e', source_pts: frame, source_time_base: { num: 1, den: 1 }, capture_time_us: time, capture_frame_index: frame, player_media_time_us: '2000000', timing_precision: 'frame_exact' as const })
function harness(overrides: Partial<Record<keyof MediaClient, unknown>> = {}) { const scope = effectScope(); let dvr!: ReturnType<typeof useAuthoritativeDvrWindow>; const fake = { createPlaybackWindow: vi.fn(), resolveCursor: vi.fn(), frameStep: vi.fn(), ...overrides } as unknown as MediaClient; scope.run(() => { dvr = useAuthoritativeDvrWindow(fake) }); return { dvr, fake, stop: () => scope.stop() } }

describe('authoritative DVR controller integration', () => {
  it('preserves descriptor while refresh is pending and installs success', async () => { const h = harness(); h.fake.createPlaybackWindow = vi.fn().mockResolvedValueOnce(descriptor('a')).mockResolvedValueOnce(descriptor('b')); await h.dvr.create({ schema_version: '1.0.0', capture_session_id: 's', mode: 'archive', target_capture_time_us: '1' }); const pending = h.dvr.create({ schema_version: '1.0.0', capture_session_id: 's', mode: 'archive', target_capture_time_us: '2' }); expect(h.dvr.current.value?.playback_window_id).toBe('a'); await pending; expect(h.dvr.current.value?.playback_window_id).toBe('b'); h.stop() })
  it('resolve error retains prior anchor and sets error', async () => { const h = harness(); h.fake.resolveCursor = vi.fn().mockRejectedValue(new Error('offline')); await expect(h.dvr.resolve({} as never)).resolves.toBeNull(); expect(h.dvr.anchor.value).toBeNull(); expect(h.dvr.status.value).toBe('error'); h.stop() })
  it.each(['SAMPLE_NOT_FOUND', 'CAPTURE_GAP'])('blocks %s without local mutation', async code => { const h = harness(); h.fake.createPlaybackWindow = vi.fn().mockResolvedValue(descriptor('a')); await h.dvr.create({ schema_version: '1.0.0', capture_session_id: 's', mode: 'archive', target_capture_time_us: '1' }); h.fake.resolveCursor = vi.fn().mockResolvedValue(anchor('1')); await h.dvr.resolve({} as never); h.fake.frameStep = vi.fn().mockRejectedValue(new MediaApiError(code as never, code, 400)); await h.dvr.step('next', () => ({}) as never); expect(h.dvr.status.value).toBe('gap'); expect(h.dvr.current.value?.playback_window_id).toBe('a'); expect(h.fake.createPlaybackWindow).toHaveBeenCalledTimes(1); h.stop() })
  it('boundary recovers with one window refresh and retry', async () => { const h = harness(); h.fake.createPlaybackWindow = vi.fn().mockResolvedValue(descriptor('a')); await h.dvr.create({ schema_version: '1.0.0', capture_session_id: 's', mode: 'archive', target_capture_time_us: '1' }); h.fake.resolveCursor = vi.fn().mockResolvedValue(anchor('1', '12')); await h.dvr.resolve({} as never); h.fake.frameStep = vi.fn().mockRejectedValueOnce(new MediaApiError('WINDOW_BOUNDARY', 'b', 409, { target_capture_time_us: '20' })).mockResolvedValue(anchor('2')); await expect(h.dvr.step('next', target => ({ schema_version: '1.0.0', capture_session_id: 's', mode: 'archive', target_capture_time_us: target }))).resolves.toMatchObject({ capture_frame_index: '2' }); expect(h.fake.frameStep).toHaveBeenCalledTimes(2); expect(h.fake.createPlaybackWindow).toHaveBeenCalledTimes(2); h.stop() })
})
