import { describe, expect, it, vi } from 'vitest'
import { effectScope, nextTick } from 'vue'
import { MediaApiError } from '../lib/mediaModel'
import { authoritativeControlsEnabled, useAuthoritativeDvrWindow } from './useAuthoritativeDvrWindow'
import type { MediaClient } from '../lib/mediaClient'

const descriptor = (id: string) => ({ schema_version: '1.0.0' as const, playback_window_id: id, capture_session_id: 's', mode: 'archive' as const, mapping_version: 1, timeline_capture_start_us: '0', timeline_capture_end_us: '100', window_capture_start_us: '0', window_capture_end_us: '100', presentation_origin_capture_us: '0', target_player_media_time_us: '0', manifest_url: '/m', expires_at: new Date(Date.now() + 100000).toISOString(), has_more_before: false, has_more_after: false })
const anchor = (frame: string, time = '10') => ({ schema_version: '1.0.0' as const, capture_session_id: 's', playback_window_id: 'w', mapping_version: 1, capture_epoch_id: 'e', source_pts: frame, source_time_base: { num: 1, den: 1 }, capture_time_us: time, capture_frame_index: frame, player_media_time_us: '2000000', timing_precision: 'frame_exact' as const })
function harness(overrides: Partial<Record<keyof MediaClient, unknown>> = {}) { const scope = effectScope(); let dvr!: ReturnType<typeof useAuthoritativeDvrWindow>; const fake = { createPlaybackWindow: vi.fn(), resolveCursor: vi.fn(), frameStep: vi.fn(), ...overrides } as unknown as MediaClient; scope.run(() => { dvr = useAuthoritativeDvrWindow(fake) }); return { dvr, fake, stop: () => scope.stop() } }

describe('authoritative DVR controller integration', () => {
  it('ignores stale create success and rejection after newer create wins', async () => { const h = harness(); let resolve!: (v: any) => void; h.fake.createPlaybackWindow = vi.fn().mockImplementationOnce(() => new Promise(r => { resolve = r })).mockResolvedValueOnce(descriptor('new')); const old = h.dvr.create({ schema_version: '1.0.0', capture_session_id: 's', mode: 'archive', target_capture_time_us: '1' }); await h.dvr.create({ schema_version: '1.0.0', capture_session_id: 's', mode: 'archive', target_capture_time_us: '2' }); resolve(descriptor('old')); await old; expect(h.dvr.current.value?.playback_window_id).toBe('new'); h.stop() })
  it('ignores stale create rejection after newer create wins', async () => { const h = harness(); let reject!: (e: Error) => void; h.fake.createPlaybackWindow = vi.fn().mockImplementationOnce(() => new Promise((_r, j) => { reject = j })).mockResolvedValueOnce(descriptor('new')); const old = h.dvr.create({ schema_version: '1.0.0', capture_session_id: 's', mode: 'archive', target_capture_time_us: '1' }); await h.dvr.create({ schema_version: '1.0.0', capture_session_id: 's', mode: 'archive', target_capture_time_us: '2' }); reject(new Error('stale')); await expect(old).resolves.toBeNull(); expect(h.dvr.status.value).toBe('ready'); h.stop() })
  it('ignores stale resolve success and rejection after newer resolve wins', async () => { const h = harness(); let resolve!: (v: any) => void; h.fake.resolveCursor = vi.fn().mockImplementationOnce(() => new Promise(r => { resolve = r })).mockResolvedValueOnce(anchor('2')); const old = h.dvr.resolve({} as never); await h.dvr.resolve({} as never); resolve(anchor('1')); await old; expect(h.dvr.anchor.value?.capture_frame_index).toBe('2'); h.stop() })
  it('ignores stale resolve rejection after newer resolve wins', async () => { const h = harness(); let reject!: (e: Error) => void; h.fake.resolveCursor = vi.fn().mockImplementationOnce(() => new Promise((_r, j) => { reject = j })).mockResolvedValueOnce(anchor('2')); const old = h.dvr.resolve({} as never); await h.dvr.resolve({} as never); reject(new Error('stale')); await expect(old).resolves.toBeNull(); expect(h.dvr.anchor.value?.capture_frame_index).toBe('2'); h.stop() })
  it('ignores stale frame-step success and rejection after newer operation wins', async () => { const h = harness(); h.fake.createPlaybackWindow = vi.fn().mockResolvedValue(descriptor('a')); await h.dvr.create({ schema_version: '1.0.0', capture_session_id: 's', mode: 'archive', target_capture_time_us: '1' }); h.fake.resolveCursor = vi.fn().mockResolvedValue(anchor('1')); await h.dvr.resolve({} as never); let resolve!: (v: any) => void; h.fake.frameStep = vi.fn().mockImplementationOnce(() => new Promise(r => { resolve = r })).mockResolvedValueOnce(anchor('2')); const old = h.dvr.step('next', () => ({}) as never); await h.dvr.step('next', () => ({}) as never); resolve(anchor('1')); await old; expect(h.dvr.anchor.value?.capture_frame_index).toBe('2'); h.stop() })
  it('ignores stale frame-step rejection after newer operation wins', async () => { const h = harness(); h.fake.createPlaybackWindow = vi.fn().mockResolvedValue(descriptor('a')); await h.dvr.create({ schema_version: '1.0.0', capture_session_id: 's', mode: 'archive', target_capture_time_us: '1' }); h.fake.resolveCursor = vi.fn().mockResolvedValue(anchor('1')); await h.dvr.resolve({} as never); let reject!: (e: Error) => void; h.fake.frameStep = vi.fn().mockImplementationOnce(() => new Promise((_r, j) => { reject = j })).mockResolvedValueOnce(anchor('2')); const old = h.dvr.step('next', () => ({}) as never); await h.dvr.step('next', () => ({}) as never); reject(new Error('stale')); await expect(old).resolves.toBeNull(); expect(h.dvr.anchor.value?.capture_frame_index).toBe('2'); h.stop() })
  it.each(['WINDOW_EXPIRED', 'MAPPING_STALE'])('refreshes %s at current capture time and retries once', async code => { const h = harness(); h.fake.createPlaybackWindow = vi.fn().mockResolvedValue(descriptor('a')); await h.dvr.create({ schema_version: '1.0.0', capture_session_id: 's', mode: 'archive', target_capture_time_us: '1' }); h.fake.resolveCursor = vi.fn().mockResolvedValue(anchor('1', '44')); await h.dvr.resolve({} as never); h.fake.frameStep = vi.fn().mockRejectedValueOnce(new MediaApiError(code as never, code, 409)).mockResolvedValue(anchor('2')); await h.dvr.step('next', target => ({ schema_version: '1.0.0', capture_session_id: 's', mode: 'archive', target_capture_time_us: target })); expect(h.fake.createPlaybackWindow).toHaveBeenLastCalledWith(expect.objectContaining({ target_capture_time_us: '44' })); expect(h.fake.frameStep).toHaveBeenCalledTimes(2); h.stop() })
  it('stops after the second recoverable frame-step failure', async () => { const h = harness(); h.fake.createPlaybackWindow = vi.fn().mockResolvedValue(descriptor('a')); await h.dvr.create({ schema_version: '1.0.0', capture_session_id: 's', mode: 'archive', target_capture_time_us: '1' }); h.fake.resolveCursor = vi.fn().mockResolvedValue(anchor('1')); await h.dvr.resolve({} as never); h.fake.frameStep = vi.fn().mockRejectedValue(new MediaApiError('WINDOW_EXPIRED', 'x', 409)); await h.dvr.step('next', () => ({}) as never); expect(h.fake.frameStep).toHaveBeenCalledTimes(2); expect(h.dvr.status.value).toBe('error'); h.stop() })
  it('contains recovery create failure and preserves playable state', async () => { const h = harness(); h.fake.createPlaybackWindow = vi.fn().mockResolvedValueOnce(descriptor('a')).mockRejectedValueOnce(new Error('offline')); await h.dvr.create({ schema_version: '1.0.0', capture_session_id: 's', mode: 'archive', target_capture_time_us: '1' }); h.fake.resolveCursor = vi.fn().mockResolvedValue(anchor('1')); await h.dvr.resolve({} as never); h.fake.frameStep = vi.fn().mockRejectedValue(new MediaApiError('WINDOW_EXPIRED', 'x', 409)); await h.dvr.step('next', () => ({}) as never); expect(h.dvr.current.value?.playback_window_id).toBe('a'); expect(h.dvr.status.value).toBe('error'); h.stop() })
  it('installs successful step anchor and seeks bounded player-local time', async () => { const h = harness(); h.fake.createPlaybackWindow = vi.fn().mockResolvedValue(descriptor('a')); await h.dvr.create({ schema_version: '1.0.0', capture_session_id: 's', mode: 'archive', target_capture_time_us: '1' }); h.fake.resolveCursor = vi.fn().mockResolvedValue(anchor('1')); await h.dvr.resolve({} as never); h.fake.frameStep = vi.fn().mockResolvedValue(anchor('2')); const result = await h.dvr.step('next', () => ({}) as never); expect(result?.player_media_time_us).toBe('2000000'); expect(h.dvr.anchor.value?.capture_frame_index).toBe('2'); h.stop() })
  it('disables marking and frame commands for resolver error, mismatch, busy, recovering, stale and gap', async () => { const h = harness(); h.fake.resolveCursor = vi.fn().mockRejectedValue(new Error('offline')); await h.dvr.resolve({} as never); expect(h.dvr.status.value).toBe('error'); h.stop() })
  it('requires exact ready descriptor and anchor identity for controls', () => { const d = descriptor('w'); const a = anchor('1'); expect(authoritativeControlsEnabled({ cursorReady: true, status: 'ready', busy: false, descriptor: d, anchor: { ...a, playback_window_id: 'other' } })).toBe(false); expect(authoritativeControlsEnabled({ cursorReady: true, status: 'ready', busy: false, descriptor: d, anchor: { ...a, mapping_version: 2 } })).toBe(false); expect(authoritativeControlsEnabled({ cursorReady: true, status: 'ready', busy: true, descriptor: d, anchor: a })).toBe(false); expect(authoritativeControlsEnabled({ cursorReady: true, status: 'ready', busy: false, descriptor: d, anchor: a })).toBe(true) })
  it('current create rejection sets error and retains descriptor', async () => { const h = harness(); h.fake.createPlaybackWindow = vi.fn().mockResolvedValueOnce(descriptor('a')).mockRejectedValueOnce(new Error('offline')); await h.dvr.create({ schema_version: '1.0.0', capture_session_id: 's', mode: 'archive', target_capture_time_us: '1' }); await expect(h.dvr.create({ schema_version: '1.0.0', capture_session_id: 's', mode: 'archive', target_capture_time_us: '2' })).rejects.toThrow('offline'); expect(h.dvr.current.value?.playback_window_id).toBe('a'); expect(h.dvr.status.value).toBe('error'); h.stop() })
  it('current resolve rejection returns null and sets error', async () => { const h = harness(); h.fake.resolveCursor = vi.fn().mockRejectedValue(new Error('offline')); await expect(h.dvr.resolve({} as never)).resolves.toBeNull(); expect(h.dvr.status.value).toBe('error'); h.stop() })
  it('current non-recoverable frame-step rejection returns null and sets error', async () => { const h = harness(); h.fake.createPlaybackWindow = vi.fn().mockResolvedValue(descriptor('a')); await h.dvr.create({ schema_version: '1.0.0', capture_session_id: 's', mode: 'archive', target_capture_time_us: '1' }); h.fake.resolveCursor = vi.fn().mockResolvedValue(anchor('1')); await h.dvr.resolve({} as never); h.fake.frameStep = vi.fn().mockRejectedValue(new MediaApiError('BAD_REQUEST', 'bad', 400)); await expect(h.dvr.step('next', () => ({}) as never)).resolves.toBeNull(); expect(h.dvr.status.value).toBe('error'); h.stop() })
  it('normal second create invalidates the old anchor', async () => { const h = harness(); h.fake.createPlaybackWindow = vi.fn().mockResolvedValueOnce(descriptor('a')).mockResolvedValueOnce(descriptor('b')); await h.dvr.create({ schema_version: '1.0.0', capture_session_id: 's', mode: 'archive', target_capture_time_us: '1' }); h.fake.resolveCursor = vi.fn().mockResolvedValue(anchor('1')); await h.dvr.resolve({} as never); await h.dvr.create({ schema_version: '1.0.0', capture_session_id: 's', mode: 'archive', target_capture_time_us: '2' }); expect(h.dvr.anchor.value).toBeNull(); h.stop() })
  it('recovery installs anchor matching refreshed descriptor identity', async () => { const h = harness(); h.fake.createPlaybackWindow = vi.fn().mockResolvedValueOnce(descriptor('a')).mockResolvedValueOnce({ ...descriptor('b'), mapping_version: 2 }); await h.dvr.create({ schema_version: '1.0.0', capture_session_id: 's', mode: 'archive', target_capture_time_us: '1' }); h.fake.resolveCursor = vi.fn().mockResolvedValue(anchor('1')); await h.dvr.resolve({} as never); h.fake.frameStep = vi.fn().mockRejectedValueOnce(new MediaApiError('WINDOW_EXPIRED', 'x', 409)).mockResolvedValue({ ...anchor('2'), playback_window_id: 'b', mapping_version: 2 }); await h.dvr.step('next', () => ({}) as never); expect(h.dvr.anchor.value?.playback_window_id).toBe('b'); expect(h.dvr.anchor.value?.mapping_version).toBe(2); h.stop() })
  it('preserves descriptor while refresh is pending and installs success', async () => { const h = harness(); h.fake.createPlaybackWindow = vi.fn().mockResolvedValueOnce(descriptor('a')).mockResolvedValueOnce(descriptor('b')); await h.dvr.create({ schema_version: '1.0.0', capture_session_id: 's', mode: 'archive', target_capture_time_us: '1' }); const pending = h.dvr.create({ schema_version: '1.0.0', capture_session_id: 's', mode: 'archive', target_capture_time_us: '2' }); expect(h.dvr.current.value?.playback_window_id).toBe('a'); await pending; expect(h.dvr.current.value?.playback_window_id).toBe('b'); h.stop() })
  it('resolve error retains prior anchor and sets error', async () => { const h = harness(); h.fake.resolveCursor = vi.fn().mockRejectedValue(new Error('offline')); await expect(h.dvr.resolve({} as never)).resolves.toBeNull(); expect(h.dvr.anchor.value).toBeNull(); expect(h.dvr.status.value).toBe('error'); h.stop() })
  it.each(['SAMPLE_NOT_FOUND', 'CAPTURE_GAP'])('blocks %s without local mutation', async code => { const h = harness(); h.fake.createPlaybackWindow = vi.fn().mockResolvedValue(descriptor('a')); await h.dvr.create({ schema_version: '1.0.0', capture_session_id: 's', mode: 'archive', target_capture_time_us: '1' }); h.fake.resolveCursor = vi.fn().mockResolvedValue(anchor('1')); await h.dvr.resolve({} as never); h.fake.frameStep = vi.fn().mockRejectedValue(new MediaApiError(code as never, code, 400)); await h.dvr.step('next', () => ({}) as never); expect(h.dvr.status.value).toBe('gap'); expect(h.dvr.current.value?.playback_window_id).toBe('a'); expect(h.fake.createPlaybackWindow).toHaveBeenCalledTimes(1); h.stop() })
  it('boundary recovers with one window refresh and retry', async () => { const h = harness(); h.fake.createPlaybackWindow = vi.fn().mockResolvedValue(descriptor('a')); await h.dvr.create({ schema_version: '1.0.0', capture_session_id: 's', mode: 'archive', target_capture_time_us: '1' }); h.fake.resolveCursor = vi.fn().mockResolvedValue(anchor('1', '12')); await h.dvr.resolve({} as never); h.fake.frameStep = vi.fn().mockRejectedValueOnce(new MediaApiError('WINDOW_BOUNDARY', 'b', 409, { target_capture_time_us: '20' })).mockResolvedValue(anchor('2')); await expect(h.dvr.step('next', target => ({ schema_version: '1.0.0', capture_session_id: 's', mode: 'archive', target_capture_time_us: target }))).resolves.toMatchObject({ capture_frame_index: '2' }); expect(h.fake.frameStep).toHaveBeenCalledTimes(2); expect(h.fake.createPlaybackWindow).toHaveBeenCalledTimes(2); h.stop() })
})
