// Runtime-first Phase 1B domain slice; Prisma-backed resolvers are intentionally explicit.
// @ts-nocheck
import { GraphQLError } from 'graphql'
import { db } from '@volleyball-monitoring/db'
import { builder } from './builder.js'

const error = (message, code) => { throw new GraphQLError(message, { extensions: { code } }) }
const identity = (ctx) => ctx.user ?? error('Authentication required', 'UNAUTHENTICATED')
const operator = async (ctx, matchId) => { const u = identity(ctx); if (u.role === 'ADMIN') return u; const member = await db.matchMember.findUnique({ where: { matchId_userId: { matchId, userId: u.id } } }); if (!member || member.role !== 'OPERATOR') error('Insufficient role', 'FORBIDDEN'); return u }
const clean = (value) => String(value ?? '').trim()
const key = (value) => clean(value).toLocaleLowerCase()

const Health = builder.objectRef('Health'); const Viewer = builder.objectRef('Viewer'); const Player = builder.objectRef('Player'); const Team = builder.objectRef('Team'); const Roster = builder.objectRef('MatchRosterEntry'); const Assignment = builder.objectRef('CourtSideAssignment'); const Set = builder.objectRef('MatchSet'); const Match = builder.objectRef('Match')
Health.implement({ fields: (t) => ({ status: t.string({ resolve: () => 'ok' }), service: t.string({ resolve: () => 'volleyball-monitoring-server' }) }) })
Viewer.implement({ fields: (t) => ({ id: t.id({ resolve: (u) => u.id }), email: t.string({ resolve: (u) => u.email }), displayName: t.string({ resolve: (u) => u.displayName }) }) })
Player.implement({ fields: (t) => ({ id: t.id({ resolve: (p) => p.id }), name: t.string({ resolve: (p) => p.name }) }) })
Team.implement({ fields: (t) => ({ id: t.id({ resolve: (x) => x.id }), name: t.string({ resolve: (x) => x.name }), shortName: t.string({ resolve: (x) => x.shortName }), players: t.field({ type: [Player], resolve: (x) => db.player.findMany({ where: { teamId: x.id }, orderBy: { name: 'asc' } }) }) }) })
Roster.implement({ fields: (t) => ({ id: t.id({ resolve: (x) => x.id }), jerseyNumber: t.string({ resolve: (x) => x.jerseyNumber }), displayNameSnapshot: t.string({ nullable: true, resolve: (x) => x.displayNameSnapshot }), player: t.field({ type: Player, nullable: true, resolve: (x) => x.playerId ? db.player.findUnique({ where: { id: x.playerId } }) : null }) }) })
Assignment.implement({ fields: (t) => ({ id: t.id({ resolve: (x) => x.id }), effectiveFromRallyOrdinal: t.int({ resolve: (x) => x.effectiveFromRallyOrdinal }), effectiveToRallyOrdinal: t.int({ nullable: true, resolve: (x) => x.effectiveToRallyOrdinal }), leftTeam: t.field({ type: Team, resolve: (x) => db.team.findUniqueOrThrow({ where: { id: x.leftTeamId } }) }), rightTeam: t.field({ type: Team, resolve: (x) => db.team.findUniqueOrThrow({ where: { id: x.rightTeamId } }) }) }) })
Set.implement({ fields: (t) => ({ id: t.id({ resolve: (x) => x.id }), setNumber: t.int({ resolve: (x) => x.setNumber }), assignments: t.field({ type: [Assignment], resolve: (x) => db.courtSideAssignment.findMany({ where: { setId: x.id }, orderBy: { effectiveFromRallyOrdinal: 'asc' } }) }) }) })
Match.implement({ fields: (t) => ({ id: t.id({ resolve: (x) => x.id }), title: t.string({ resolve: (x) => x.title }), venue: t.string({ nullable: true, resolve: (x) => x.venue }), teams: t.field({ type: [Team], resolve: (x) => db.matchTeam.findMany({ where: { matchId: x.id }, include: { team: true } }).then((r) => r.map((v) => v.team)) }), roster: t.field({ type: [Roster], resolve: (x) => db.matchRosterEntry.findMany({ where: { matchId: x.id }, orderBy: { jerseyNumber: 'asc' } }) }), sets: t.field({ type: [Set], resolve: (x) => db.matchSet.findMany({ where: { matchId: x.id }, orderBy: { setNumber: 'asc' } }) }) }) })

const RosterInput = builder.inputType('RosterInput', { fields: (t) => ({ name: t.string({ required: true }), jerseyNumber: t.string({ required: true }) }) }); const TeamInput = builder.inputType('TeamInput', { fields: (t) => ({ name: t.string({ required: true }), shortName: t.string({ required: true }), roster: t.field({ type: [RosterInput], required: true }) }) }); const SetupInput = builder.inputType('CreateMatchSetupInput', { fields: (t) => ({ title: t.string({ required: true }), venue: t.string(), scheduledAt: t.field({ type: 'DateTime' }), leftTeam: t.field({ type: TeamInput, required: true }), rightTeam: t.field({ type: TeamInput, required: true }) }) }); const SwapInput = builder.inputType('SwapCourtSidesInput', { fields: (t) => ({ setId: t.id({ required: true }), effectiveFromRallyOrdinal: t.int({ required: true }) }) })

builder.queryType({ fields: (t) => ({
  health: t.field({ type: Health, resolve: () => ({}) }),
  viewer: t.field({ type: Viewer, resolve: (_r, _a, c) => { const u = identity(c); return db.user.findUniqueOrThrow({ where: { id: u.id } }) } }),
  matches: t.field({ type: [Match], resolve: async (_r, _a, c) => { const u = identity(c); return db.match.findMany({ where: u.role === 'ADMIN' ? {} : { members: { some: { userId: u.id } } }, orderBy: { createdAt: 'desc' } }) } }),
  match: t.field({ type: Match, nullable: true, args: { id: t.arg.id({ required: true }) }, resolve: async (_r, a, c) => { const u = identity(c); return db.match.findFirst({ where: { id: String(a.id), ...(u.role === 'ADMIN' ? {} : { members: { some: { userId: u.id } } }) } }) } }),
}) })

builder.mutationType({ fields: (t) => ({
  createMatchSetup: t.field({ type: Match, args: { input: t.arg({ type: SetupInput, required: true }) }, resolve: async (_r, a, c) => { const u = identity(c); if (!['ADMIN', 'OPERATOR'].includes(u.role)) error('Insufficient role', 'FORBIDDEN'); const i = a.input; if (!clean(i.title) || key(i.leftTeam.name) === key(i.rightTeam.name)) error('Invalid match setup', 'BAD_USER_INPUT'); for (const team of [i.leftTeam, i.rightTeam]) { if (!clean(team.name) || !clean(team.shortName)) error('Invalid team', 'BAD_USER_INPUT'); const ns = new Set(), js = new Set(); for (const p of team.roster) { const n = key(p.name), j = key(p.jerseyNumber); if (!n || !j || ns.has(n) || js.has(j)) error('Duplicate roster entry', 'BAD_USER_INPUT'); ns.add(n); js.add(j) } } return db.$transaction(async (tx) => { const m = await tx.match.create({ data: { title: clean(i.title), ...(i.venue ? { venue: clean(i.venue) } : {}), ...(i.scheduledAt ? { scheduledAt: new Date(i.scheduledAt) } : {}) } }); const teams = []; for (const input of [i.leftTeam, i.rightTeam]) { const team = await tx.team.create({ data: { name: clean(input.name), shortName: clean(input.shortName) } }); teams.push(team); await tx.matchTeam.create({ data: { matchId: m.id, teamId: team.id } }); for (const p of input.roster) { const player = await tx.player.create({ data: { teamId: team.id, name: clean(p.name) } }); await tx.matchRosterEntry.create({ data: { matchId: m.id, teamId: team.id, playerId: player.id, jerseyNumber: clean(p.jerseyNumber), displayNameSnapshot: clean(p.name) } }) } } await tx.matchMember.create({ data: { matchId: m.id, userId: u.id, role: 'OPERATOR' } }); const s = await tx.matchSet.create({ data: { matchId: m.id, setNumber: 1 } }); await tx.courtSideAssignment.create({ data: { setId: s.id, effectiveFromRallyOrdinal: 1, leftTeamId: teams[0].id, rightTeamId: teams[1].id } }); return m }) } }),
  swapCourtSides: t.field({ type: Set, args: { input: t.arg({ type: SwapInput, required: true }) }, resolve: async (_r, a, c) => { const ordinal = a.input.effectiveFromRallyOrdinal; if (ordinal < 1) error('Invalid rally ordinal', 'BAD_USER_INPUT'); const set = await db.matchSet.findUnique({ where: { id: String(a.input.setId) } }); if (!set) error('Set not found', 'NOT_FOUND'); await operator(c, set.matchId); return db.$transaction(async (tx) => { const current = await tx.courtSideAssignment.findFirst({ where: { setId: set.id, effectiveToRallyOrdinal: null }, orderBy: { effectiveFromRallyOrdinal: 'desc' } }); if (!current) error('Assignment not found', 'NOT_FOUND'); if (ordinal <= current.effectiveFromRallyOrdinal) error('Ordinal must advance', 'BAD_USER_INPUT'); await tx.courtSideAssignment.update({ where: { id: current.id }, data: { effectiveToRallyOrdinal: ordinal - 1 } }); await tx.courtSideAssignment.create({ data: { setId: set.id, effectiveFromRallyOrdinal: ordinal, leftTeamId: current.rightTeamId, rightTeamId: current.leftTeamId } }); return tx.matchSet.findUniqueOrThrow({ where: { id: set.id } }) }) } }),
}) })

export const schema = builder.toSchema({ sortSchema: true })
