<script setup lang="ts">
import { ANNOTATION_COMMANDS, formatBindingForDisplay, type AnnotationAction } from '~/utils/annotationHotkeys'
const props = withDefaults(defineProps<{ bindings: Record<string, string>; state: 'IDLE'|'OPEN'|'READY'|'SUBMITTED'|'VOIDED'; canMark: boolean; lastKeyPoint: boolean; commandReady?: boolean; pendingCommand?: boolean }>(), { commandReady: true, pendingCommand: false })
const emit = defineEmits<{ action: [AnnotationAction] }>()
function reason(action: AnnotationAction) { if (props.pendingCommand) return '已有待送出操作'; if (props.commandReady === false) return '標註操作暫時不可用'; if (action === 'service' && (!['IDLE', 'SUBMITTED', 'VOIDED'].includes(props.state) || !props.canMark)) return !['IDLE', 'SUBMITTED', 'VOIDED'].includes(props.state) ? '已有開啟中的回合' : '游標尚未由伺服器確認'; if (action === 'contact' && (props.state !== 'OPEN' || !props.canMark)) return props.state !== 'OPEN' ? '尚未開啟回合' : '游標尚未由伺服器確認'; if (action.startsWith('close_') && (props.state !== 'OPEN' || !props.lastKeyPoint)) return props.state !== 'OPEN' ? '尚未開啟回合' : '沒有伺服器確認的最後 key point'; if (action === 'submit' && props.state !== 'READY') return '提交狀態尚未就緒'; return '' }
</script>
<template><div class="command-strip" aria-label="Annotation commands"><template v-for="command in ANNOTATION_COMMANDS" :key="command.action"><i v-if="command.action === 'close_left'" class="command-divider" aria-hidden="true" /><button type="button" :class="{ 'submit-command': command.action === 'submit' }" :disabled="Boolean(reason(command.action))" :title="reason(command.action) || '可用'" @click="emit('action', command.action)"><kbd>{{ formatBindingForDisplay(bindings[command.action] ?? '') }}</kbd><span>{{ command.label }}</span><small class="command-reason">{{ reason(command.action) }}</small></button></template></div></template>
<style scoped>
.command-strip{display:grid;grid-template-columns:.72fr .85fr 1px 1.15fr 1.15fr 1fr 1.1fr;gap:6px;align-items:center;padding:7px 12px;border-top:1px solid #292f35;background:#111419}.command-strip button{min-width:0;min-height:39px;display:flex;align-items:center;justify-content:center;gap:7px;padding:5px 8px;border:1px solid #4a535d;border-radius:6px;background:#20252b;color:#edf1f4;cursor:pointer}.command-strip button:not(:disabled):hover{border-color:#6b7681;background:#282e35}.command-strip button:focus-visible{outline:2px solid #62a9ff;outline-offset:2px}.command-strip button:disabled{opacity:.35;cursor:not-allowed}.command-strip button span{overflow:hidden;font-size:.7rem;text-overflow:ellipsis;white-space:nowrap}.command-strip kbd{min-width:24px;padding:2px 5px;border:1px solid #59636d;border-bottom-width:2px;border-radius:4px;background:#12161a;color:#fff;font:700 .68rem "Cascadia Mono",Consolas,monospace;text-align:center}.command-strip .submit-command{margin-left:4px;border-color:#299c64;background:#17643f}.command-divider{width:1px;height:26px;background:#30363d}.command-reason{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap}@media(max-width:1050px){.command-strip button span{font-size:.64rem}}
</style>
