import { describe, expect, it } from 'vitest'
import { mount } from '@vue/test-utils'
import DvrTimelineDock from './DvrTimelineDock.vue'
const timeline = { captureSessionId: 's', captureStartTimeUs: '1000', liveEdgeCaptureTimeUs: null, timelineVersion: '1', availableRanges: [{ startUs: '1000', endUs: '2000', discontinuity: 0 }, { startUs: '3000', endUs: '4000', discontinuity: 1 }] }
describe('DvrTimelineDock mounted interactions', () => {
  it('emits exact target and blocks gaps', async () => { const w = mount(DvrTimelineDock, { props: { timeline, playhead: null } }); const lane = w.find('[role="slider"]'); Object.defineProperty(lane.element, 'getBoundingClientRect', { value: () => ({ left: 0, width: 100 }) }); await lane.trigger('click', { clientX: 25 }); expect(w.emitted('seek')?.[0]).toEqual(['1750']); await lane.trigger('click', { clientX: 62 }); expect(w.emitted('seek')).toHaveLength(1) })
  it('bounds zoom/pan and reset restores centered view', async () => { const w = mount(DvrTimelineDock, { props: { timeline, playhead: null } }); const dock = w.find('.timeline-dock'); const viewport = () => w.find('.timeline-dock__viewport').text(); expect(viewport()).toContain('1.00x · pan 0'); for (let i = 0; i < 50; i++) await dock.trigger('wheel', { deltaY: -100 }); expect(viewport()).toContain('8.00x'); await dock.element.dispatchEvent(new WheelEvent('wheel', { deltaY: 100, shiftKey: true })); expect(viewport()).not.toContain('pan 0'); for (let i = 0; i < 50; i++) await dock.element.dispatchEvent(new WheelEvent('wheel', { deltaY: 100, shiftKey: true })); expect(Number(viewport().match(/pan (-?\d+)/)?.[1])).toBe(-50); await w.find('button').trigger('click'); expect(viewport()).toContain('1.00x · pan 0') })
  it('renders discontinuity marker', () => { const w = mount(DvrTimelineDock, { props: { timeline, playhead: null } }); expect(w.findAll('.timeline-dock__gap').length).toBeGreaterThan(0) })
})
