logLevel: info
api: yes
apiAddress: :9997
rtsp: yes
rtspAddress: :8554
rtmp: yes
rtmpAddress: :1935
srt: yes
srtAddress: :8890
hls: yes
hlsAddress: :8888
hlsAllowOrigins: ['*']
hlsVariant: lowLatency
hlsAlwaysRemux: yes
pathDefaults:
  record: yes
  recordPath: /recordings/%path/%Y-%m-%d_%H-%M-%S-%f
  recordFormat: fmp4
  recordPartDuration: 500ms
  recordMaxPartSize: 50M
  recordSegmentDuration: 2s
  recordDeleteAfter: 0s
  runOnRecordSegmentComplete: python3 /usr/local/bin/media-indexer-hook.py "$MTX_SEGMENT_PATH"
paths:
  all_others:
