import { spawn } from 'node:child_process';
import { parseFfprobePayload, type FfprobePayload } from '@volleyball-monitoring/media/sample-index';
export type FfprobeErrorCode='SPAWN_FAILED'|'NONZERO_EXIT'|'TIMEOUT'|'CANCELLED'|'OUTPUT_TOO_LARGE'|'INVALID_JSON'|'INVALID_PROBE';
export class FfprobeError extends Error { constructor(public readonly code:FfprobeErrorCode,msg:string){super(msg);} }
export type ProbeRunner=(executable:string,args:string[],o:{shell:false;timeoutMs:number;maxOutputBytes:number;signal?:AbortSignal})=>Promise<{code:number;stdout:string;stderr:string}>;
export type SpawnLike = typeof spawn;
export type ProbeOptions={ executable?:string; timeoutMs?:number; maxOutputBytes?:number; signal?:AbortSignal; runner?:ProbeRunner };
export const createNodeProbeRunner=(spawnImpl:SpawnLike=spawn):ProbeRunner=> (exe,args,o)=>new Promise((resolve,reject)=>{const p=spawnImpl(exe,args,{shell:false});let out='',err='',done=false;const finish=(fn:(v:unknown)=>void,v:unknown)=>{if(done)return;done=true;fn(v)};const kill=(e:FfprobeError)=>{if(!done)p.kill();finish(reject,e)};const t=setTimeout(()=>kill(new FfprobeError('TIMEOUT','timeout')),o.timeoutMs);const abort=()=>kill(new FfprobeError('CANCELLED','cancelled'));if(o.signal?.aborted)return abort();o.signal?.addEventListener('abort',abort,{once:true});p.stdout.on('data',d=>{out+=d;if(Buffer.byteLength(out)>o.maxOutputBytes)kill(new FfprobeError('OUTPUT_TOO_LARGE','output too large'))});p.stderr.on('data',d=>{err+=d;if(Buffer.byteLength(err)>o.maxOutputBytes)kill(new FfprobeError('OUTPUT_TOO_LARGE','stderr too large'))});p.on('error',e=>kill(new FfprobeError('SPAWN_FAILED',e.message)));p.on('close',code=>{clearTimeout(t);o.signal?.removeEventListener('abort',abort);finish(resolve,{code:code??-1,stdout:out,stderr:err})});});
const nodeRunner=createNodeProbeRunner();
export async function runFfprobe(filePath:string,o:ProbeOptions={}):Promise<ReturnType<typeof parseFfprobePayload>>{const args=['-v','error','-print_format','json','-show_entries','stream=codec_type,time_base:frame=media_type,pts,pkt_duration,key_frame',filePath];const ro:{shell:false;timeoutMs:number;maxOutputBytes:number;signal?:AbortSignal}={shell:false,timeoutMs:o.timeoutMs??10000,maxOutputBytes:o.maxOutputBytes??2_000_000};if(o.signal)ro.signal=o.signal;const r=await (o.runner??nodeRunner)(o.executable??'ffprobe',args,ro);if(r.code!==0)throw new FfprobeError('NONZERO_EXIT',r.stderr);let j:FfprobePayload;try{j=JSON.parse(r.stdout)}catch{throw new FfprobeError('INVALID_JSON','invalid json')}try{return parseFfprobePayload(j)}catch{throw new FfprobeError('INVALID_PROBE','invalid probe')};}
